apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS products_db;
    CREATE DATABASE IF NOT EXISTS orders_db;
    CREATE DATABASE IF NOT EXISTS payments_db;
    -- Autoriser l'accès aux autres services
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'root';
    FLUSH PRIVILEGES;
    USE products_db;
    CREATE TABLE IF NOT EXISTS product (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        price DECIMAL(10,2) NOT NULL
    );

    USE orders_db;
    CREATE TABLE IF NOT EXISTS `order` (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        product_id BIGINT NOT NULL,
        quantity INT NOT NULL,
        total_price DECIMAL(10,2) NOT NULL,
        status VARCHAR(50) NOT NULL
    );

    USE payments_db;
    CREATE TABLE IF NOT EXISTS payment (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        order_id BIGINT NOT NULL,
        amount DECIMAL(10,2) NOT NULL,
        payment_status VARCHAR(50) NOT NULL
    );

    -- Users + droits
    CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'root';
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
    FLUSH PRIVILEGES;

    -- Test data
    USE products_db;
    INSERT INTO product (name, price) VALUES ('Laptop', 999.99);
    INSERT INTO product (name, price) VALUES ('Smartphone', 599.99);

    USE orders_db;
    INSERT INTO `order` (product_id, quantity, total_price, status)
    VALUES (1, 2, 1999.98, 'PENDING');

    USE payments_db;
    INSERT INTO payment (order_id, amount, payment_status)
    VALUES (1, 1999.98, 'COMPLETED');
