apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      automountServiceAccountToken: false
      containers:
        - name: product
          image: kawtar2/product-service:latest
          imagePullPolicy: Always  # Force le pull de la nouvelle image
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/products_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081 # 8082 ou 8083 selon le microservice
            initialDelaySeconds: 180  # ⬅️ augmente ce délai
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 6

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
