name: CI/CD Ecommerce Platform

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Give execute permission to mvnw
        run: chmod +x ./mvnw

      - name: Build JAR for product-service
        run: |
          cd product-service
          ../mvnw clean package -DskipTests
          cd ..

      - name: Build JAR for order-service
        run: |
          cd order-service
          ../mvnw clean package -DskipTests
          cd ..

      - name: Build JAR for payment-service
        run: |
          cd payment-service
          ../mvnw clean package -DskipTests
          cd ..

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push product-service image
        run: |
          docker build -t kawtar2/product-service ./product-service
          docker push kawtar2/product-service

      - name: Build and push order-service image
        run: |
          docker build -t kawtar2/order-service ./order-service
          docker push kawtar2/order-service

      - name: Build and push payment-service image
        run: |
          docker build -t kawtar2/payment-service ./payment-service
          docker push kawtar2/payment-service

      - name: Deploy to Kubernetes in local VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/kawtar/ecommerce-deploy
            kubectl apply -f k8s/
